# -*- coding: utf-8 -*-
import os
import sys
sys.path.append('RaspiDrink')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "RaspiDrink.settings")
from django.core.wsgi import get_wsgi_application
SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
sys.path.append(SITE_ROOT)
application = get_wsgi_application()
from webgui.models import Bottle, Cocktail, Cocktailinfo

# create bottles
vodka = Bottle.objects.create(name="Vodka", slot=1)
jagger = Bottle.objects.create(name="Jägermeister", slot=2)
martini = Bottle.objects.create(name="Martini", slot=3)
rhum = Bottle.objects.create(name="Rhum", slot=4)
tequila = Bottle.objects.create(name="tequila", slot=5)
whisky = Bottle.objects.create(name="Whisky", slot=6)
triple_sec = Bottle.objects.create(name="Triple sec", slot=7)
gin = Bottle.objects.create(name="Gin", slot=8)
curacao_bleu = Bottle.objects.create(name="Curaçao bleu", slot=9)
sucre_canne = Bottle.objects.create(name="Sucre de canne", slot=10)
coka = Bottle.objects.create(name="Coka", slot=11)
citron = Bottle.objects.create(name="Jus de citron", slot=12)
sirop_fraise = Bottle.objects.create(name="Sirop de fraise", slot=13)
perrier = Bottle.objects.create(name="Perrier", slot=14)
orange = Bottle.objects.create(name="Orange", slot=15)

# create cocktails
vodka_orange = Cocktail.objects.create(name="Vodka Orange")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=vodka_orange, volume=5)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=orange, cocktail=vodka_orange, volume=15)
info_bottle2.save()

diesel = Cocktail.objects.create(name="Diesel")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=diesel, volume=5)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=coka, cocktail=diesel, volume=13)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=citron, cocktail=diesel, volume=2)
info_bottle3.save()

james_bond = Cocktail.objects.create(name="James Bond")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=james_bond, volume=3)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=martini, cocktail=james_bond, volume=10)
info_bottle2.save()

devil = Cocktail.objects.create(name="Devil")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=devil, volume=3)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=jagger, cocktail=devil, volume=3)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=sirop_fraise, cocktail=devil, volume=2)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=coka, cocktail=devil, volume=12)
info_bottle4.save()

volcan = Cocktail.objects.create(name="Volcan")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=volcan, volume=3)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=coka, cocktail=volcan, volume=3)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=sirop_fraise, cocktail=volcan, volume=14)
info_bottle3.save()

whysky_orange = Cocktail.objects.create(name="Whisky Orange")
info_bottle1 = Cocktailinfo(bottle=whisky, cocktail=whysky_orange, volume=5)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=orange, cocktail=whysky_orange, volume=15)
info_bottle2.save()

whysky_coka = Cocktail.objects.create(name="Whisky Coka")
info_bottle1 = Cocktailinfo(bottle=whisky, cocktail=whysky_coka, volume=5)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=coka, cocktail=whysky_coka, volume=15)
info_bottle2.save()

tequila_sunrise = Cocktail.objects.create(name="Tequila Sunrise")
info_bottle1 = Cocktailinfo(bottle=tequila, cocktail=tequila_sunrise, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=sirop_fraise, cocktail=tequila_sunrise, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=orange, cocktail=tequila_sunrise, volume=14)
info_bottle3.save()

cuba_libre = Cocktail.objects.create(name="Cuba Libre")
info_bottle1 = Cocktailinfo(bottle=rhum, cocktail=cuba_libre, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=citron, cocktail=cuba_libre, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=coka, cocktail=cuba_libre, volume=14)
info_bottle3.save()

rhum_orange = Cocktail.objects.create(name="Rhum Orange")
info_bottle1 = Cocktailinfo(bottle=rhum, cocktail=rhum_orange, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=orange, cocktail=rhum_orange, volume=16)
info_bottle2.save()

punch = Cocktail.objects.create(name="Punch")
info_bottle1 = Cocktailinfo(bottle=rhum, cocktail=punch, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=sucre_canne, cocktail=punch, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=citron, cocktail=punch, volume=2)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=orange, cocktail=punch, volume=12)
info_bottle4.save()

nd42_street = Cocktail.objects.create(name="42nd Street")
info_bottle1 = Cocktailinfo(bottle=whisky, cocktail=nd42_street, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=triple_sec, cocktail=nd42_street, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=martini, cocktail=nd42_street, volume=1)
info_bottle3.save()

long_island = Cocktail.objects.create(name="Long Island")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=long_island, volume=2)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=gin, cocktail=long_island, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=rhum, cocktail=long_island, volume=2)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=triple_sec, cocktail=long_island, volume=2)
info_bottle4.save()
info_bottle5 = Cocktailinfo(bottle=tequila, cocktail=long_island, volume=2)
info_bottle5.save()
info_bottle6 = Cocktailinfo(bottle=citron, cocktail=long_island, volume=1)
info_bottle6.save()
info_bottle7 = Cocktailinfo(bottle=coka, cocktail=long_island, volume=9)
info_bottle7.save()

margarita = Cocktail.objects.create(name="Margarita")
info_bottle1 = Cocktailinfo(bottle=tequila, cocktail=margarita, volume=5)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=triple_sec, cocktail=margarita, volume=3)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=citron, cocktail=margarita, volume=2)
info_bottle3.save()

planteur = Cocktail.objects.create(name="Planteur")
info_bottle1 = Cocktailinfo(bottle=rhum, cocktail=planteur, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=citron, cocktail=planteur, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=sirop_fraise, cocktail=planteur, volume=2)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=orange, cocktail=planteur, volume=12)
info_bottle4.save()

daiquiri = Cocktail.objects.create(name="Daiquiri")
info_bottle1 = Cocktailinfo(bottle=rhum, cocktail=daiquiri, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=citron, cocktail=daiquiri, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=sucre_canne, cocktail=daiquiri, volume=1)
info_bottle3.save()

gin_fizz = Cocktail.objects.create(name="Gin Fizz")
info_bottle1 = Cocktailinfo(bottle=gin, cocktail=gin_fizz, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=citron, cocktail=gin_fizz, volume=3)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=sucre_canne, cocktail=gin_fizz, volume=2)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=perrier, cocktail=gin_fizz, volume=11)
info_bottle4.save()

halloween = Cocktail.objects.create(name="Halloween")
info_bottle1 = Cocktailinfo(bottle=whisky, cocktail=halloween, volume=3)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=perrier, cocktail=halloween, volume=6)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=orange, cocktail=halloween, volume=3)
info_bottle3.save()

cocaine_liquide = Cocktail.objects.create(name="Cocaine liquide")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=cocaine_liquide, volume=2)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=tequila, cocktail=cocaine_liquide, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=curacao_bleu, cocktail=cocaine_liquide, volume=2)
info_bottle3.save()

kamikaze = Cocktail.objects.create(name="Kamikaze")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=kamikaze, volume=2)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=triple_sec, cocktail=kamikaze, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=citron, cocktail=kamikaze, volume=2)
info_bottle3.save()

rainbow_shot_the_sheriff = Cocktail.objects.create(name="Rainbow shot the sheriff")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=rainbow_shot_the_sheriff, volume=3)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=curacao_bleu, cocktail=rainbow_shot_the_sheriff, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=sirop_fraise, cocktail=rainbow_shot_the_sheriff, volume=3)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=orange, cocktail=rainbow_shot_the_sheriff, volume=10)
info_bottle4.save()

aquarium = Cocktail.objects.create(name="Aquarium")
info_bottle1 = Cocktailinfo(bottle=martini, cocktail=aquarium, volume=2)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=rhum, cocktail=aquarium, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=tequila, cocktail=aquarium, volume=2)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=curacao_bleu, cocktail=aquarium, volume=2)
info_bottle4.save()
info_bottle5 = Cocktailinfo(bottle=sucre_canne, cocktail=aquarium, volume=2)
info_bottle5.save()

alaska_ice_tea = Cocktail.objects.create(name="Alaska Ice Tea")
info_bottle1 = Cocktailinfo(bottle=vodka, cocktail=alaska_ice_tea, volume=2)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=rhum, cocktail=alaska_ice_tea, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=triple_sec, cocktail=alaska_ice_tea, volume=2)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=gin, cocktail=alaska_ice_tea, volume=2)
info_bottle4.save()
info_bottle5 = Cocktailinfo(bottle=curacao_bleu, cocktail=alaska_ice_tea, volume=2)
info_bottle5.save()

jagerinha = Cocktail.objects.create(name="Jägerinha")
info_bottle1 = Cocktailinfo(bottle=jagger, cocktail=jagerinha, volume=2)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=sucre_canne, cocktail=jagerinha, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=citron, cocktail=jagerinha, volume=2)
info_bottle3.save()

jazz_negroni = Cocktail.objects.create(name="Jazz Negroni")
info_bottle1 = Cocktailinfo(bottle=jagger, cocktail=jazz_negroni, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=orange, cocktail=jazz_negroni, volume=16)
info_bottle2.save()

jager_club = Cocktail.objects.create(name="Jäger Club")
info_bottle1 = Cocktailinfo(bottle=jagger, cocktail=jager_club, volume=3)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=perrier, cocktail=jager_club, volume=12)
info_bottle2.save()

meister_on_mars = Cocktail.objects.create(name="Meister on Mars")
info_bottle1 = Cocktailinfo(bottle=jagger, cocktail=meister_on_mars, volume=3)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=curacao_bleu, cocktail=meister_on_mars, volume=2)
info_bottle2.save()
info_bottle3 = Cocktailinfo(bottle=sirop_fraise, cocktail=meister_on_mars, volume=1)
info_bottle3.save()
info_bottle4 = Cocktailinfo(bottle=orange, cocktail=meister_on_mars, volume=2)
info_bottle4.save()

jagger_coke = Cocktail.objects.create(name="Jagger Coke")
info_bottle1 = Cocktailinfo(bottle=jagger, cocktail=jagger_coke, volume=4)
info_bottle1.save()
info_bottle2 = Cocktailinfo(bottle=coka, cocktail=jagger_coke, volume=16)
info_bottle2.save()
